config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  
  delete '/logout', to: 'sessions#logout'

  get '/auth/google_oauth2/callback', to: 'sessions#omniauth'

  get '/search', to: 'devices#search', as: 'search' 

  get '/filter_by_location', to: 'rooms#filter_by_location'   

  root('static#home')

  get '/automations', to: 'automations#all'
  resources :devices do
    resources :automations
  end
  
  delete '/devices/:id/automations/:id', to: 'automations#destroy'

  resources :users do
    resources :rooms
  end

  resources :rooms
  

  get '/404', to: "errors#not_found"
  get '/422', to: "errors#unacceptable"
  get '/500', to: "errors#internal_error"
  
end

app/models/device.rb
class Device < ApplicationRecord
    belongs_to :user
    has_many :automations
    has_many :rooms, through: :automations

    validates :name, :brand, :description, :quantity, presence: true
    scope :search, -> (query) { self.where("name LIKE ?", "%#{query}%") }

    
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
    before_action :redirect_if_not_logged_in, only: [:new, :create, :index, :show, :edit, :update, :destroy]
    
    def search
        @devices = current_user.devices.search(params[:device])
        render :index
    end

    
    def index
        @devices = current_user.devices
    end

    def show
        @device = current_user.devices.find(params[:id])
    end

    def new
        @device = current_user.devices.build
    end

    def create
    
        @device = current_user.devices.build(device_params)
        if @device.save!
            redirect_to device_path(@device)
        else
            flash.now[:notice] = "Device DID NOT save: "
            render :new
        end
    end

    def edit
        @device = current_user.devices.find(params[:id])
    end

    def update 
        @device = current_user.devices.find(params[:id])
        @device.update(device_params)

        if @device.valid?
            redirect_to device_path(@device)
        else 
            render :edit
        end
    end

    def destroy
        @device = current_user.devices.find(params[:id])
        @device.destroy
        redirect_to devices_path
    end

    private

    def device_params
        params.require(:device).permit(:name, :brand, :type, :model, :description, :quantity, :user_id)
    end

end

app/views/devices/edit.html.erb
<center>
<div class="fancy-text">
<div class="card-one" style="width: 30rem;">
<div class="card-body">
    <h1> Edit Device </h1>
    <%= form_for(@device) do |f| %>
        <%= f.label :name %>
        <%= f.text_field :name %><br>
        <%= f.label :brand %>
        <%= f.text_field :brand %><br>
        <%= f.label :model %>
        <%= f.text_field :model %><br>
        <%= f.label :description %>
        <%= f.text_field :description %><br>
        <%= f.label :quantity %>
        <%= f.text_field :quantity %><br>
        <%= f.submit 'Edit Device' %>
    <% end %>

    <%= button_to "Delete", device_path(@device), method: "delete"%>
</div>
</div>
</div>
</center>

app/views/devices/index.html.erb
<center>
<div class="fancy-text">
    <h1> Devices </h1>
    <br>
    <% if !@devices.empty? %>
        <% @devices.each do |device| %>
        <div class="card-one" style="width: 20rem;">
        <div class="card-body">
        <h4> <%= link_to device.name, device_path(device), class: 'my-btn-sm'%> </h4>
        </div>
        </div>
        <br>
    <% end%>
<% else %>
<div class="card-one" style="width: 20rem;">
<div class="card-body">
         You currently have no devices! Create your first 
        <%= link_to 'Device', new_device_path, class: 'my-btn-sm' %>. 
    </div>
    </div>
<% end %>
</div>
</center>

app/views/devices/new.html.erb
<% flash.each do |type, msg| %>
    <div class="alert alert-info">
        <%= msg %>
        <%= render partial: 'errors/errors', locals: {model: @device} %>
    </div>
<% end %>
<center>
<div class="fancy-text">
<div class="card-one" style="width: 30rem;">
<div class="card-body">
<h1> New Device </h1>
<%= form_for(@device) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %><br>
    <%= f.label :brand %>
    <%= f.text_field :brand %><br>
    <%= f.label :model %>
    <%= f.text_field :model %><br>
    <%= f.label :description %>
    <%= f.text_field :description %><br>
    <%= f.label :quantity %>
    <%= f.text_field :quantity %><br>
    <%= f.submit 'Create Device' %>
<% end %>
</div>
</div>
</div>
</center>

app/views/devices/order_by_quantity.html.erb
<h1> Devices </h1>
<ul>
<% @devices.each do |device| %>
    <li>
    <%= device.name %> - <%= device.quantity %>
    </li>
<% end %>
</ul>

app/views/devices/show.html.erb
<center>
<div class="fancy-text">    
    <div class="card-one" style="width: 30rem;">
    <div class="card-body">
        <h1> <%= @device.name %> </h1>
        <p> Model: <%= @device.model %> </p>
        <p> Description: <%= @device.description %> </p>
        <p> Brand: <%= @device.brand %> </p>
        <p> Quantity: <%= @device.quantity %> </p>
        <%= link_to "Edit", edit_device_path(@device), class: 'my-btn-sm'%>
        <br>
        <%= button_to "Delete", device_path(@device), method: "delete"%>
    </div>
    </div>
    <br>
    <% if !@device.automations.empty? %>
    <div class="card-one" style="width: 20rem;">
    <div class="card-body">
    <%= link_to 'New Automation', new_device_automation_path(@device), class: 'my-btn-sm' %>
    <br>
    <br>
    <h4> Automations for <%= @device.name %> </h4>
    </div>
    </div>
    <br>
        <% @device.automations.each do |automation| %> 
            <div class="card-one" style="width: 20rem;">
            <div class="card-body">
            <%= link_to automation.name, device_automation_path(@device, automation), class: 'my-btn-sm'%>
            </div>
            </div>
            <br>
        <%end %>
    <% else %>
        <div class="card-one" style="width: 20rem;">
        <div class="card-body">
        <p> You currently have no automations. <%= link_to 'Create new automation', new_device_automation_path(@device), class: 'my-btn-sm' %> for this device.</p>
            </div>
            </div>
        <% end %> 
</div>  
</center>