config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  
  delete '/logout', to: 'sessions#logout'

  get '/auth/google_oauth2/callback', to: 'sessions#omniauth'

  get '/search', to: 'devices#search', as: 'search' 

  get '/filter_by_location', to: 'rooms#filter_by_location'   

  root('static#home')

  get '/automations', to: 'automations#all'
  resources :devices do
    resources :automations
  end
  
  delete '/devices/:id/automations/:id', to: 'automations#destroy'

  resources :users do
    resources :rooms
  end

  resources :rooms
  

  get '/404', to: "errors#not_found"
  get '/422', to: "errors#unacceptable"
  get '/500', to: "errors#internal_error"
  
end

app/models/automation.rb
class Automation < ApplicationRecord
    belongs_to :room
    belongs_to :device
    has_one :user, through: :device

    validates :name, :if_action, :then_action, :room_id, presence: true 
    
end

app/controllers/automations_controller.rb
class AutomationsController < ApplicationController
    before_action :redirect_if_not_logged_in, only: [:new, :create, :index, :show, :edit, :update, :destroy]

    def new
        device = current_user.devices.find_by(id: params[:device_id])
        @automation = device.automations.new
        #@automation.device = Device.find_by(id: params[:device_id])
    end

    def create
        device = current_user.devices.find_by(id: params[:device_id])
        @automation = device.automations.new(automation_params)
        @automation.device = Device.find_by(id: params[:device_id])
        #binding.pry
        if @automation.save
            redirect_to device_automation_path(@automation.device, @automation)
        else
            flash.now[:notice] = "Automation DID NOT save. Fill in all fields. "
            render :new
        end
    end

    def index
        @device = current_user.devices.find_by(id: params[:device_id])
        device = current_user.devices.find_by(id: params[:device_id])
        @automations = device.automations.all
    end

    def all
        @automations = current_user.automations.all
    end

    def show
        @device = current_user.devices.find_by(id: params[:device_id])
        @automation = current_user.automations.find_by(id: params[:id])
    end

    def edit
        @device = Device.find_by(id: params[:device_id])
        @automation = current_user.automations.find_by(id: params[:id])
        #binding.pry
    end

    def update
        @device = Device.find_by(id: params[:device_id])
        @automation = current_user.automations.find_by(id: params[:id])
        @automation.update(automation_params)
        if @automation.save
                redirect_to device_automation_path(@automation.device, @automation)
        else
            render :edit
        end
    end

    def destroy
        @automation = Automation.find_by(id: params[:id])
        @automation.destroy
        redirect_to device_automations_path
    end

    private

    def automation_params
        params.require(:automation).permit(:name, :if_action, :then_action, :room_id, :device_id)
    end
end

app/views/automations/all.html.erb
<center>
<div class="fancy-text">
    <% if !@automations.empty? %>
    <h3> Automations for All Devices </h3>
    <br>
    <% @automations.each do |automation| %>
        <div class="card-one" style="width: 20rem;">
        <div class="card-body">
        <h4> <%= link_to automation.name,  device_automation_path(automation.device_id, automation), class: 'my-btn-sm'%> </h4>
        </div>
        </div>
        <br>
    <% end %>
    <% else %>
    <div class="card-one" style="width: 20rem;">
    <div class="card-body">
    <h5> There are currently no automations. <h5>
    </div>
    </div>
    <% end %>
</div>
</center>

app/views/automations/edit.html.erb
<center>
    <div class="card" style="width: 30rem;">
    <div class="card-body">
        <h1>Update Automation</h1>
        <%= form_with(model: [:device, @automation])  do |f| %>
        <%= f.label "Name:" %>
        <%= f.text_field :name %><br>
        <%= f.label "Start Time:" %>
        <%= f.collection_select :if_action, time_options, :to_s, :to_s, prompt: true %><br>
        <%= f.label "Action: "%>
        <%= f.text_field :then_action %><br>
        <%= f.label "Room:" %>
        <%= f.collection_select :room_id, current_user.rooms.all, :id, :name, prompt: true %><br>
        <%= f.submit 'Update Automation' %>
        <% end %>
        <br>
        <%= button_to "DELETE AUTOMATION", device_automation_path(@automation.device, @automation), method: "delete" %>
        <br>
    </div>
    </div>
    </center>

app/views/automations/index.html.erb
<center>
    <h1> <%= @device.name %> Automations </h1>
    <% if !@automations.empty? %>
        <% @automations.each do |automation| %>
            <div class="card" style="width: 30rem;">
            <div class="card-body">
            <h4> <%= link_to automation.name,  device_automation_path(automation.device_id, automation) %> </h4>
            </div>
            </div>
        <br>
        <% end %>
    <% else %>
        <br>
        <div class="card" style="width: 30rem;">
        <div class="card-body">
        <h4> There are currently no Automations for this device.  <%= link_to 'Create new automation', new_device_automation_path(@device) %>. </h4>
        </div>
        </div>
    <% end %>
</center>

app/views/automations/new.html.erb
<% flash.each do |type, msg| %>
    <div class="alert alert-info">
        <%= msg %>
        <%= render partial: 'errors/errors', locals: {model: @automation} %>
    </div>
<% end %>
<center>
<div class="fancy-text">
<div class="card-one" style="width: 30rem;">
<div class="card-body">

<h1>New Automation</h1>
<%= form_with(model: [:device, @automation]) do |f| %>
    <%= f.label "Name:" %>
    <%= f.text_field :name %><br>
    <%= f.label "Start Time:" %>
    <%= f.collection_select :if_action, time_options, :to_s, :to_s, prompt: true %><br>
    <%= f.label "Action: "%>
    <%= f.text_field :then_action %><br>
    <%= f.label "Room:" %>
    <%= f.collection_select :room_id, current_user.rooms.all, :id, :name, prompt: true %><br>
    <%= f.submit 'Create Automation' %>
<% end %>

</div>
</div>
</div>
</center>

app/views/automations/show.html.erb
<center>
<div class="fancy-text">
    <div class="card-one" style="width: 20rem;">
    <div class="card-body">
        <h1> <%=@automation.name %> </h1>
        <p> Time: <%= @automation.if_action %> </p> 
        <p> Action: <%= @automation.then_action %> </p>
        <p> Device: <%= @automation.device.name %> </p>
        <br>
        <%= link_to "Edit", edit_device_automation_path(@automation.device, @automation), class: 'my-btn-sm'%><br>
        <br>
        <%= button_to "DELETE AUTOMATION", device_automation_path(@automation.device, @automation), method: "delete" %>
        <br>
        <%= link_to "All #{@automation.room.name} Automations", room_path(@automation.room), class: 'my-btn-sm' %><br>
        <br>
        <%= link_to "Back to #{@device.name}", device_path(@device), class: 'my-btn-sm' %>
    </div>
    </div>
</div>
</center>