config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  
  delete '/logout', to: 'sessions#logout'

  get '/auth/google_oauth2/callback', to: 'sessions#omniauth'

  get '/search', to: 'devices#search', as: 'search' 

  get '/filter_by_location', to: 'rooms#filter_by_location'   

  root('static#home')

  get '/automations', to: 'automations#all'
  resources :devices do
    resources :automations
  end
  
  delete '/devices/:id/automations/:id', to: 'automations#destroy'

  resources :users do
    resources :rooms
  end

  resources :rooms
  

  get '/404', to: "errors#not_found"
  get '/422', to: "errors#unacceptable"
  get '/500', to: "errors#internal_error"
  
end

app/models/Room.rb
class Room < ApplicationRecord
    belongs_to :user, optional: true
    has_many :automations 
    has_many :devices, through: :automations

    validates :name, presence: true
    scope :filter_by_location, -> (indoor) { where indoor: true }
    
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
    before_action :redirect_if_not_logged_in, only: [:new, :create, :edit, :update]
    
    def filter_by_location
       @rooms = current_user.rooms.filter_by_location(@rooms)
    end


    def index  
        @rooms = current_user.rooms
    end

    def show
        @room = current_user.rooms.find_by(id: params[:id])
    end

    def new
        @room = current_user.rooms.build
    end

    def create
        @room = current_user.rooms.new(room_params)
        if @room.save
            redirect_to room_path(@room)
        else
            flash.now[:notice] = "Room DID NOT save: "
            render :new
        end
    end

    def edit
        @room = current_user.rooms.find(params[:id])
    end
    
    def update 
        @room = current_user.rooms.find(params[:id])
        @room.update(room_params)
        if @room.valid?
            redirect_to rooms_path
        else
            render :edit
        end
    end

    def destroy
        @room = current_user.rooms.find(params[:id])
        @room.destroy
        redirect_to rooms_path
    end

    private

    def room_params
        params.require(:room).permit(:name, :indoor, :outdoor, :user_id)
    end

end

app/views/rooms/edit.html.erb
<h1> New Room </h1>
<%= form_for(@room) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %><br>
    <%= f.label :indoor %>
    <%= f.check_box :indoor, {}, true, false %> <br>
    <%= f.label :outdoor %>
    <%= f.check_box :outdoor, {}, true, false %> <br>
    <%= f.submit 'Create Room' %>
<% end %>

app/views/rooms/filter_by_location.html.erb
<center>
<div class="fancy-text">
<h3> Indoor Living Spaces </h3>
<br>
<%= link_to 'All Living Spaces', rooms_path, class: 'my-btn-sm' %>
<% @rooms.each do |room| %>
    <div class="card-one" style="width: 18rem;">
    <div class="card-body">
    <%= link_to room.name, room_path(room), class: 'my-btn-sm'%>
    </div>
    </div>
    <br>
<% end%>
</div>
</center>

app/views/rooms/index.html.erb
<center>
<div class="fancy-text">
<div class= "custom-title"> My Home </div>

<% if !@rooms.empty? %>
<%= link_to('Indoor Rooms', filter_by_location_path, class: "my-btn-sm")%>
<br>
<br>
    <% @rooms.each do |room| %>
        <div class="card-one" style="width: 18rem;">
        <div class="card-body">
        <%= link_to(room.name, room_path(room), class: "my-btn")%>
        </div>
        </div>
        <br>
    <% end%>
<% else %>
    <div class="card-one" style="width: 30rem;">
    <div class="card-body">
    You currently have no rooms. Create your first <%= link_to 'Room', new_room_path, class: 'my-btn-sm'%>.
<% end %>
</div>
</center>

app/views/rooms/new.html.erb
<center>
<div class="fancy-text">
    <% flash.each do |type, msg| %>
    <div class="alert alert-info">
        <%= msg %>
        <%= render partial: 'errors/errors', locals: {model: @room} %>
    </div>
    <% end %>

    <div class="card-one" style="width: 20rem;">
    <div class="card-body">
    <h1> New Room </h1>
    <%= form_for(@room) do |f| %>
        <%= f.label :name %>
        <%= f.text_field :name %><br>
        <%= f.label :indoor %>
        <%= f.check_box :indoor, {}, true, false %> <br>
        <%= f.label :outdoor %>
        <%= f.check_box :outdoor, {}, true, false %> <br>
        <%= f.submit 'Create Room' %>
    <% end %>
    </div>
    </div>
</div>
</center>

app/views/rooms/show.html.erb
<center>
<div class="fancy-text">
    <div class="card-one" style="width: 20rem;">
    <div class="card-body">
        <div class= "custom-title">
            <%= @room.name %>
        </div>
        <% if @room.indoor == true %>
            <p> Indoor </p>
        <% else %>
            <p> Outdoor </p>
        <% end %>
        <%= link_to "Edit", edit_room_path(@room), class: "my-btn-sm"%>
        <%= button_to "Delete", room_path(@room), method: "delete", class: "my-btn-sm"%>
    </div>
    </div>
    <br>
    <br>
    <% if !@room.automations.empty? %>
        <div class="card-one" style="width: 30rem;">
        <div class="card-body">
        <div class="custom-title-sm"> Automations for <%= @room.name %>: </div> </div> </div>
        <br>
        <% @room.automations.each do |automation|%>
            <div class="card-one" style="width: 20rem;">
            <div class="card-body">
                <p> <%= link_to automation.name,  device_automation_path(automation.device_id, automation),  class: "my-btn-sm"%> </p>
            </div>
            </div>
        <% end %>
    <% else %>
        <div class="card-body">
        <div class="card-one" style="width: 30rem;">
        <br>
            Looks like this room has no automations! Select a device and <%= link_to "create new automation", devices_path, class: "my-btn-sm" %>. 
        <br>
        </div>
        </div>
    <% end %>
</div>
</center>