config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  
  delete '/logout', to: 'sessions#logout'

  get '/auth/google_oauth2/callback', to: 'sessions#omniauth'

  get '/search', to: 'devices#search', as: 'search' 

  get '/filter_by_location', to: 'rooms#filter_by_location'   

  root('static#home')

  get '/automations', to: 'automations#all'
  resources :devices do
    resources :automations
  end
  
  delete '/devices/:id/automations/:id', to: 'automations#destroy'

  resources :users do
    resources :rooms
  end

  resources :rooms
  

  get '/404', to: "errors#not_found"
  get '/422', to: "errors#unacceptable"
  get '/500', to: "errors#internal_error"
  
end

app/views/layouts/_nav.html.erb
<% if logged_in? %>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
<div class="fancy-text">
<div id="mySidenav" class="sidenav">
  <%= form_with(url: search_path, method: 'get', class: 'd-flex') do |f|%>
    <%= f.text_field :device, class: "form-control me-2", placeholder: "Search for Device" %>
    <%= f.submit :Search, class: "my-search-btn" %>
  <% end %>
  <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
  <%= link_to 'My Home', rooms_path, class: 'nav-link active' %>
  <%= link_to 'New Living Space', new_room_path, class: 'nav-link active'%>
  <%= link_to 'Devices', devices_path, class: 'nav-link active'%>
  <%= link_to 'Create New Device', new_device_path, class: 'nav-link active' %>
  <%= link_to 'Automations', automations_path, class: 'nav-link active' %>
  <br>
  <center> <%= (button_to 'Logout', logout_path, class: 'nav-link active', method: :delete) if logged_in? %></center>
</div>

<div id="main">
  <span style="font-size:30px;cursor:pointer" onclick="openNav()">&#9776; </span>
</div>

<script>
function openNav() {
  document.getElementById("mySidenav").style.width = "250px";
  document.getElementById("main").style.marginLeft = "250px";
}

function closeNav() {
  document.getElementById("mySidenav").style.width = "0";
  document.getElementById("main").style.marginLeft= "0";
}
</script>
  </div>
</body>
</html> 
<% end %>

app/views/layouts/application.html.erb
<%= stylesheet_link_tag 'style.css' %>
<!DOCTYPE html>
<html>
  <head>
    
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>

  <body>
  <%=  render partial: "layouts/nav" %>
  <%= yield %>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>